apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: backend-latency
  namespace: default
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      app: backend
  delay:
    latency: "200ms"
    correlation: "100"
    jitter: "0ms"
  duration: "5m"
